- name: virtualbox apt-key add
  apt_key:
    url: http://download.virtualbox.org/virtualbox/debian/oracle_vbox_2016.asc
    state: present
- name: virtualbox add-apt-repository
  apt_repository:
    repo: deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian focal contrib
    state: present
- name: vagrant apt-key add
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
- name: vagrant add-apt-repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com focal main
    state: present
- name: apt update
  apt:
    update_cache: yes
- name: apt install vm
  apt:
    pkg:
      - virtualbox-6.1
      - vagrant
- name: vagrant plugin vagrant-disksize
  shell: vagrant plugin install vagrant-disksize
  become: no
- name: vagrant plugin vagrant-vbguest
  shell: vagrant plugin install vagrant-vbguest
  become: no
