- name: apt-key add
  apt_key:
    url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    state: present
- name: add-apt-repository
  apt_repository:
    repo: deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian focal contrib
    state: present
- name: apt update
  apt:
    update_cache: yes
- name: apt-get install vm
  apt:
    pkg:
      - virtualbox-6.1
      - vagrant
- name: vagrant plugin install vagrant-disksize
  shell: vagrant plugin install vagrant-disksize
