- name: "define lsb_release"
  shell: "lsb_release -cs"
  ignore_errors: True
  register: lsb_release

- name: Create directory for apt keyrings
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Download and install virtualbox GPG key
  shell: |
    curl -fsSL "https://www.virtualbox.org/download/oracle_vbox_2016.asc" | gpg --dearmor --yes -o /etc/apt/keyrings/virtualbox.gpg

- name: Set permissions for virtualbox GPG key
  file:
    path: /etc/apt/keyrings/virtualbox.gpg
    mode: "0644"

- name: Add virtualbox repository to sources.list.d
  lineinfile:
    path: /etc/apt/sources.list.d/virtualbox.list
    line: "deb [arch=amd64 signed-by=/etc/apt/keyrings/virtualbox.gpg] https://download.virtualbox.org/virtualbox/debian {{ lsb_release.stdout }} contrib"
    create: true

- name: Download and install vagrant GPG key
  shell: |
    curl -fsSL "https://apt.releases.hashicorp.com/gpg" | gpg --dearmor --yes -o /etc/apt/keyrings/vagrant.gpg

- name: Set permissions for vagrant GPG key
  file:
    path: /etc/apt/keyrings/vagrant.gpg
    mode: "0644"

- name: Add vagrant repository to sources.list.d
  lineinfile:
    path: /etc/apt/sources.list.d/vagrant.list
    line: "deb [arch=amd64 signed-by=/etc/apt/keyrings/vagrant.gpg] https://apt.releases.hashicorp.com {{ lsb_release.stdout }} main"
    create: true

- name: apt update
  apt:
    update_cache: yes
- name: apt install vm
  apt:
    pkg:
      - virtualbox-7.0
      - vagrant

- name: vagrant plugin vagrant-disksize
  shell: vagrant plugin install vagrant-disksize
  become: false
- name: vagrant plugin vagrant-vbguest
  shell: vagrant plugin install vagrant-vbguest
  become: false

- name: edit ~/.config/fish/config.fish
  become: false
  blockinfile:
    dest: ~/.config/fish/config.fish
    create: true
    marker: "# {mark} ANSIBLE MANAGED BLOCK vm"
    content: |
      # Vagrant
      alias v 'vagrant'
      alias vup 'vagrant up'
      alias vssh 'vagrant ssh'
      alias vstat 'vagrant status'
      alias vdest 'vagrant destroy -f'
      alias vhalt 'vagrant halt'
      alias vrelo 'vagrant reload'

      # Vbox
      alias vb 'vboxmanage'
      alias vbs 'vboxmanage list runningvms'
      alias vbsa 'vboxmanage list vms'
      alias vbc 'VBoxManage list vms | grep inaccessible | cut -d "{" -f2 | cut -d "}" -f1 | xargs -L1 VBoxManage unregistervm'
